# -------- STAGE 1: Build the application --------
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copy pom.xml and download dependencies first (better caching)
COPY pom.xml .
RUN mvn -q -e -B dependency:go-offline

# Copy the source code
COPY src ./src

# Build the JAR
RUN mvn -q -e -B package -DskipTests


# -------- STAGE 2: Run the application --------
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copy jar from build stage
COPY --from=build /app/target/*.jar app.jar

# Render uses PORT env
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
