#spring.application.name=BookMgmtSystem
## Use a placeholder for the MongoDB URI
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
## Use a placeholder for the Google API Key
#google.api.key=${GOOGLE_API_KEY}
#
## Keep the server.port as is, as Render sets the PORT env variable
#server.port=${PORT:8080}


spring.application.name=BookMgmtSystem
# Use environment variable for MongoDB URI, with fallback for local development
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://root:TLp21mPU67OeXGkv@cluster0.pb4knhz.mongodb.net/BookDB?retryWrites=true&w=majority&appName=Cluster0}
# Use a placeholder for the Google API Key
google.api.key=AIzaSyBOKlhRneyYEx8QIXRpyBKJzxOrvVMEG-0

# Keep the server.port as is, as Render sets the PORT env variable
server.port=${PORT:8080}