spring.application.name=BookMgmtSystem


spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://kalyanisunilofficial_db_user:OfvIrhtBgbLTZXBj@cluster0.vbroxdm.mongodb.net/BookDB?retryWrites=true&w=majority}


google.api.key=AIzaSyBOKlhRneyYEx8QIXRpyBKJzxOrvVMEG-0

