spring.application.name=BookMgmtSystem


spring.data.mongodb.uri=${{ SPRING_DATA_MONGODB_URI }}

google.api.key=AIzaSyBOKlhRneyYEx8QIXRpyBKJzxOrvVMEG-0


mongodb+srv://kalyanisunilofficial_db_user:OfvIrhtBgbLTZXBj@cluster0.vbroxdm.mongodb.net/BookDB?retryWrites=true&w=majority